/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alignment/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every run folder and how far it got, newest first. The frontend adopts the
         *     first one on load and offers the rest as a picker, so a user comes back to
         *     their work instead of re-running the pipeline from scratch.
         */
        get: operations["list_runs_api_alignment_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/published": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published Run
         * @description Which run the viewer is currently showing. Lets the UI label the layers
         *     instead of leaving the user to assume they belong to the selected run.
         */
        get: operations["published_run_api_alignment_published_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Run
         * @description Re-point the viewer at an already-finished run's TIFFs. `aligned_result`
         *     is one global slide_id, taken over by whichever run ran thumbnail last, so a
         *     resumed run has to reclaim it -- pointer only, no recomputation.
         */
        post: operations["publish_run_api_alignment_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/preprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Preprocess */
        post: operations["run_preprocess_api_alignment_preprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/align": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Align */
        post: operations["run_align_api_alignment_align_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/roi-eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Roi Eval */
        post: operations["run_roi_eval_api_alignment_roi_eval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Thumbnail */
        post: operations["run_thumbnail_api_alignment_thumbnail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/tus/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Extension Termination Route */
        delete: operations["extension_termination_route_api_alignment_tus__uuid__delete"];
        options?: never;
        /** Core Head Route */
        head: operations["core_head_route_api_alignment_tus__uuid__head"];
        /** Core Patch Route */
        patch: operations["core_patch_route_api_alignment_tus__uuid__patch"];
        trace?: never;
    };
    "/api/alignment/tus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extension Creation Route */
        post: operations["extension_creation_route_api_alignment_tus__post"];
        delete?: never;
        /** Core Options Route */
        options: operations["core_options_route_api_alignment_tus__options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/tus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extension Creation Route */
        post: operations["extension_creation_route_api_alignment_tus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hybrid/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hybrid Result
         * @description Read back the artifacts of the most recent run in the default output dir.
         *
         *     The UI never sends output_dir (it is a server-side override), so results
         *     always land in config.output_dir -- that is the only place to look. Returns
         *     empty fields rather than 404 when nothing has run yet: "no results" is a
         *     normal state for the panel, not an error.
         */
        get: operations["hybrid_result_api_hybrid_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hybrid/report.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hybrid Report Csv
         * @description The per-cell table, as a download. A file body, not JSON -- it is the one
         *     artifact the pathologist takes away to another tool.
         */
        get: operations["hybrid_report_csv_api_hybrid_report_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hybrid/summary.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hybrid Summary Txt
         * @description The ASCO/CAP summary as a download, alongside /result which inlines the
         *     same file for the on-screen report card. A doctor keeping the interpretation
         *     for a case needs a file, not a panel they have to keep open.
         */
        get: operations["hybrid_summary_txt_api_hybrid_summary_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hybrid/tile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Hybrid Tile */
        post: operations["run_hybrid_tile_api_hybrid_tile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hybrid/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hybrid Active
         * @description The unfinished analysis job, for a page that lost track of it.
         *
         *     job_id=None means nothing is running -- a normal state, not a 404. What
         *     finished already is read back through /result, which reads the artifacts on
         *     disk and so survives a backend restart too.
         */
        get: operations["hybrid_active_api_hybrid_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Slides
         * @description slide_ids of every slide available under SLIDES_DIR, for the picker.
         *     Returns ids only, never filesystem paths (guardrail 2).
         */
        get: operations["list_slides_api_tiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/{slide_id}.dzi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dzi */
        get: operations["get_dzi_api_tiles__slide_id__dzi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/{slide_id}_files/{level}/{col}_{row}.jpeg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tile */
        get: operations["get_tile_api_tiles__slide_id__files__level___col___row__jpeg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlignmentConfigIn
         * @description Request body accepted by every /api/alignment/* endpoint.
         *
         *     All fields are optional; anything omitted falls back to RegistrationConfig's
         *     own dataclass defaults (see config.py) so a caller only needs to send the
         *     fields that differ from the CLI default.
         */
        AlignmentConfigIn: {
            /** Run Id */
            run_id?: string | null;
            /** Project Name */
            project_name?: string | null;
            /** Czi Input Dir */
            czi_input_dir?: string | null;
            /** Input Dir */
            input_dir?: string | null;
            /** Output Dir */
            output_dir?: string | null;
            /** Reference Modality */
            reference_modality?: string | null;
            /** Modalities */
            modalities?: components["schemas"]["ModalityConfigIn"][] | null;
            preprocess?: components["schemas"]["PreprocessConfigIn"] | null;
            valis?: components["schemas"]["ValisConfigIn"] | null;
            roi?: components["schemas"]["ROIConfigIn"] | null;
            thumbnail?: components["schemas"]["ThumbnailConfigIn"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HybridActive
         * @description The analysis still executing server-side, if any.
         *
         *     A run outlives the browser tab that started it: the job id lives only in the
         *     page's memory, so a reload -- or a crash mid-run -- would otherwise leave a
         *     multi-hour job with nothing watching it, and no way back to its result except
         *     running it again. The server is the one place that knows.
         */
        HybridActive: {
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * HybridResult
         * @description What a finished hybrid run left behind, as the UI needs to show it.
         *
         *     A run writes exactly three files (hybrid_pipeline.py:349-353): report.csv,
         *     summary.txt and overlay_slide.tiff. summary.txt is small and is rendered as
         *     the report card, so it is inlined here; the CSV is a download and the TIFF is
         *     addressed by slide_id, never by path (guardrail 2).
         */
        HybridResult: {
            /** Summary */
            summary?: string | null;
            /**
             * Has Report
             * @default false
             */
            has_report: boolean;
            /** Overlay Slide Id */
            overlay_slide_id?: string | null;
        };
        /** HybridTileIn */
        HybridTileIn: {
            /** Ihc Slide Id */
            ihc_slide_id: string;
            /** Dish Slide Id */
            dish_slide_id: string;
            /** Output Dir */
            output_dir?: string | null;
            /** Merge Dir */
            merge_dir?: string | null;
            /** Roi X */
            roi_x?: number | null;
            /** Roi Y */
            roi_y?: number | null;
            /** Roi W */
            roi_w?: number | null;
            /** Roi H */
            roi_h?: number | null;
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
        };
        /**
         * JobProgress
         * @description How far a long job has got, when the job knows. Absent (None on
         *     JobStatus) whenever nothing is publishing it -- the alignment pipeline
         *     reports only step transitions, and its panel estimates from those.
         *
         *     `done`/`total` count the units named by `unit_label`; `phase` says which
         *     stretch of the run is executing, because a pipeline's last phase can be
         *     long and have no counter of its own. A client must treat done == total as
         *     "this phase's counter is exhausted", not as "the job is finished" -- only
         *     status == "done" means that.
         */
        JobProgress: {
            /** Phase */
            phase: string;
            /** Done */
            done: number;
            /** Total */
            total: number;
            /** Unit Label */
            unit_label: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Result Path */
            result_path?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Key */
            key?: string | null;
            progress?: components["schemas"]["JobProgress"] | null;
        };
        /** ModalityConfigIn */
        ModalityConfigIn: {
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Czi Filename */
            czi_filename?: string | null;
            /** Scale Factor */
            scale_factor?: number | null;
        };
        /** PreprocessConfigIn */
        PreprocessConfigIn: {
            /** Strip Height */
            strip_height?: number | null;
            /** Num Processes */
            num_processes?: number | null;
        };
        /**
         * PublishedRun
         * @description Which run the viewer's `aligned_*` slide_ids currently resolve to.
         *
         *     Those ids are global and get taken over by whichever run published last, so
         *     the layers on screen do not necessarily belong to the run selected in the
         *     panel. None means nothing has been published since the backend started.
         */
        PublishedRun: {
            /** Run Id */
            run_id?: string | null;
        };
        /** ROIConfigIn */
        ROIConfigIn: {
            /** Roi Size */
            roi_size?: number[] | null;
        };
        /**
         * RunSummary
         * @description What a run directory already contains, so the UI can resume it instead of
         *     re-running the whole pipeline.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Done */
            done: string[];
            /** Job Id */
            job_id?: string | null;
        };
        /** ThumbnailConfigIn */
        ThumbnailConfigIn: {
            /** Level */
            level?: number | null;
            /** Use Non Rigid */
            use_non_rigid?: boolean | null;
            /** Laplacian Levels */
            laplacian_levels?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValisConfigIn */
        ValisConfigIn: {
            /** Max Processed Image Dim Px */
            max_processed_image_dim_px?: number | null;
            /** Max Non Rigid Registration Dim Px */
            max_non_rigid_registration_dim_px?: number | null;
            /** Align To Reference */
            align_to_reference?: boolean | null;
            /** Reference Img F */
            reference_img_f?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_alignment_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    published_run_api_alignment_published_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedRun"];
                };
            };
        };
    };
    publish_run_api_alignment_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_preprocess_api_alignment_preprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_align_api_alignment_align_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_roi_eval_api_alignment_roi_eval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_thumbnail_api_alignment_thumbnail_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_termination_route_api_alignment_tus__uuid__delete: {
        parameters: {
            query?: never;
            header?: {
                "tus-resumable"?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    core_head_route_api_alignment_tus__uuid__head: {
        parameters: {
            query?: never;
            header?: {
                "tus-resumable"?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    core_patch_route_api_alignment_tus__uuid__patch: {
        parameters: {
            query?: {
                post_request?: boolean;
            };
            header: {
                "content-length": number;
                "upload-offset": number;
                "upload-length"?: number;
                "content-type"?: string;
                "tus-resumable"?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_creation_route_api_alignment_tus__post: {
        parameters: {
            query?: never;
            header?: {
                "upload-metadata"?: string;
                "upload-length"?: number;
                "upload-defer-length"?: number;
                "upload-concat"?: string;
                "tus-resumable"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    core_options_route_api_alignment_tus__options: {
        parameters: {
            query?: never;
            header?: {
                "tus-resumable"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_creation_route_api_alignment_tus_post: {
        parameters: {
            query?: never;
            header?: {
                "upload-metadata"?: string;
                "upload-length"?: number;
                "upload-defer-length"?: number;
                "upload-concat"?: string;
                "tus-resumable"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hybrid_result_api_hybrid_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HybridResult"];
                };
            };
        };
    };
    hybrid_report_csv_api_hybrid_report_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    hybrid_summary_txt_api_hybrid_summary_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    run_hybrid_tile_api_hybrid_tile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HybridTileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hybrid_active_api_hybrid_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HybridActive"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slides_api_tiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_dzi_api_tiles__slide_id__dzi_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_api_tiles__slide_id__files__level___col___row__jpeg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                level: number;
                col: number;
                row: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
