/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alignment/dev-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Dev Run
         * @description Fill the named run's czi_input/ with symlinks to the server-local CZIs,
         *     i.e. the same state a finished upload leaves behind. Everything downstream
         *     (paths, output isolation, slide publishing) is unchanged.
         */
        post: operations["create_dev_run_api_alignment_dev_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Every run folder and how far it got, newest first. The frontend adopts the
         *     first one on load and offers the rest as a picker, so a user comes back to
         *     their work instead of re-running the pipeline from scratch.
         */
        get: operations["list_runs_api_alignment_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Run
         * @description Re-point the viewer at an already-finished run's TIFFs. SLIDES_DIR holds
         *     one global `aligned_result`, overwritten by whichever run ran thumbnail last,
         *     so a resumed run has to reclaim it -- by symlink only, no recomputation.
         */
        post: operations["publish_run_api_alignment_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/preprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Preprocess */
        post: operations["run_preprocess_api_alignment_preprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/align": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Align */
        post: operations["run_align_api_alignment_align_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/roi-eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Roi Eval */
        post: operations["run_roi_eval_api_alignment_roi_eval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Thumbnail */
        post: operations["run_thumbnail_api_alignment_thumbnail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/tus/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Extension Termination Route */
        delete: operations["extension_termination_route_api_alignment_tus__uuid__delete"];
        options?: never;
        /** Core Head Route */
        head: operations["core_head_route_api_alignment_tus__uuid__head"];
        /** Core Patch Route */
        patch: operations["core_patch_route_api_alignment_tus__uuid__patch"];
        trace?: never;
    };
    "/api/alignment/tus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extension Creation Route */
        post: operations["extension_creation_route_api_alignment_tus__post"];
        delete?: never;
        /** Core Options Route */
        options: operations["core_options_route_api_alignment_tus__options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignment/tus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extension Creation Route */
        post: operations["extension_creation_route_api_alignment_tus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hybrid/tile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Hybrid Tile */
        post: operations["run_hybrid_tile_api_hybrid_tile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Slides
         * @description slide_ids of every slide available under SLIDES_DIR, for the picker.
         *     Returns ids only, never filesystem paths (guardrail 2).
         */
        get: operations["list_slides_api_tiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/{slide_id}.dzi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dzi */
        get: operations["get_dzi_api_tiles__slide_id__dzi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tiles/{slide_id}_files/{level}/{col}_{row}.jpeg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tile */
        get: operations["get_tile_api_tiles__slide_id__files__level___col___row__jpeg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlignmentConfigIn
         * @description Request body accepted by every /api/alignment/* endpoint.
         *
         *     All fields are optional; anything omitted falls back to RegistrationConfig's
         *     own dataclass defaults (see config.py) so a caller only needs to send the
         *     fields that differ from the CLI default.
         */
        AlignmentConfigIn: {
            /** Run Id */
            run_id?: string | null;
            /** Project Name */
            project_name?: string | null;
            /** Czi Input Dir */
            czi_input_dir?: string | null;
            /** Input Dir */
            input_dir?: string | null;
            /** Output Dir */
            output_dir?: string | null;
            /** Reference Modality */
            reference_modality?: string | null;
            /** Modalities */
            modalities?: components["schemas"]["ModalityConfigIn"][] | null;
            preprocess?: components["schemas"]["PreprocessConfigIn"] | null;
            valis?: components["schemas"]["ValisConfigIn"] | null;
            roi?: components["schemas"]["ROIConfigIn"] | null;
            thumbnail?: components["schemas"]["ThumbnailConfigIn"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HybridTileIn */
        HybridTileIn: {
            /** Ihc Path */
            ihc_path: string;
            /** Dish Path */
            dish_path: string;
            /** Output Dir */
            output_dir?: string | null;
            /** Merge Dir */
            merge_dir?: string | null;
        };
        /** JobAccepted */
        JobAccepted: {
            /** Job Id */
            job_id: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Result Path */
            result_path?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Key */
            key?: string | null;
        };
        /** ModalityConfigIn */
        ModalityConfigIn: {
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Czi Filename */
            czi_filename?: string | null;
            /** Scale Factor */
            scale_factor?: number | null;
        };
        /** PreprocessConfigIn */
        PreprocessConfigIn: {
            /** Strip Height */
            strip_height?: number | null;
            /** Num Processes */
            num_processes?: number | null;
        };
        /** ROIConfigIn */
        ROIConfigIn: {
            /** Roi Size */
            roi_size?: number[] | null;
        };
        /**
         * RunSummary
         * @description What a run directory already contains, so the UI can resume it instead of
         *     re-running the whole pipeline.
         */
        RunSummary: {
            /** Run Id */
            run_id: string;
            /** Done */
            done: string[];
            /** Job Id */
            job_id?: string | null;
        };
        /** ThumbnailConfigIn */
        ThumbnailConfigIn: {
            /** Level */
            level?: number | null;
            /** Use Non Rigid */
            use_non_rigid?: boolean | null;
            /** Laplacian Levels */
            laplacian_levels?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValisConfigIn */
        ValisConfigIn: {
            /** Max Processed Image Dim Px */
            max_processed_image_dim_px?: number | null;
            /** Max Non Rigid Registration Dim Px */
            max_non_rigid_registration_dim_px?: number | null;
            /** Align To Reference */
            align_to_reference?: boolean | null;
            /** Reference Img F */
            reference_img_f?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_dev_run_api_alignment_dev_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_alignment_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    publish_run_api_alignment_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_preprocess_api_alignment_preprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_align_api_alignment_align_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_roi_eval_api_alignment_roi_eval_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_thumbnail_api_alignment_thumbnail_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlignmentConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_termination_route_api_alignment_tus__uuid__delete: {
        parameters: {
            query?: never;
            header?: {
                "tus-resumable"?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    core_head_route_api_alignment_tus__uuid__head: {
        parameters: {
            query?: never;
            header?: {
                "tus-resumable"?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    core_patch_route_api_alignment_tus__uuid__patch: {
        parameters: {
            query?: {
                post_request?: boolean;
            };
            header: {
                "content-length": number;
                "upload-offset": number;
                "upload-length"?: number;
                "content-type"?: string;
                "tus-resumable"?: string;
            };
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_creation_route_api_alignment_tus__post: {
        parameters: {
            query?: never;
            header?: {
                "upload-metadata"?: string;
                "upload-length"?: number;
                "upload-defer-length"?: number;
                "upload-concat"?: string;
                "tus-resumable"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    core_options_route_api_alignment_tus__options: {
        parameters: {
            query?: never;
            header?: {
                "tus-resumable"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extension_creation_route_api_alignment_tus_post: {
        parameters: {
            query?: never;
            header?: {
                "upload-metadata"?: string;
                "upload-length"?: number;
                "upload-defer-length"?: number;
                "upload-concat"?: string;
                "tus-resumable"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_hybrid_tile_api_hybrid_tile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HybridTileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_slides_api_tiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_dzi_api_tiles__slide_id__dzi_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tile_api_tiles__slide_id__files__level___col___row__jpeg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slide_id: string;
                level: number;
                col: number;
                row: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
